<?php

/**
 * @file
 * Contains spielstand_views.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function spielstand_views_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the spielstand_views module.
    case 'help.page.spielstand_views':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a Views Field that checks if the current player is part of Mannschaft 1') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function spielstand_views_theme() {
  return [
    'spielstand_views' => [
      'render element' => 'children',
    ],
  ];
}
